[22기 이준영] 장바구니 Product 삭제 기능 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #12
Opened 2021-07-09 07:58 UTC by Pratiable

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 Product 삭제 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 Product 개별 삭제 기능
- 장바구니 Product 전체 삭제 기능 (프론트와 상의하여 0으로 설정)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 삭제 시 path parameter를 이렇게 사용해도 될까요...?

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

![스크린샷 2021-07-09 오후 4 39 25](https://user-images.githubusercontent.com/77120067/125044256-c05ee600-e0d6-11eb-8833-7870d29b26a4.png)
![스크린샷 2021-07-09 오후 4 51 06](https://user-images.githubusercontent.com/77120067/125044304-cd7bd500-e0d6-11eb-838f-2b3e4c3ea341.png)

2021-07-12 08:36 UTC, Kang-kyunghun requested changes

2021-07-12 08:36 UTC, Kang-kyunghun commented on orders/views.py
> +                    item.delete()
```suggestion
                iCartItem.objects.filter(user=signed_user).delete()
```
queryset도 delete() method가 적용됩니다.

2021-07-12 08:36 UTC, Kang-kyunghun commented on orders/views.py
> +                return JsonResponse({'message':'INVALID_ITEM'}, status=400)
```suggestion
            if not CartItem.objects.filter(pk=cart_item, user=signed_user).exists():
                return JsonResponse({'message':'NOT_FOUND'}, status=404)
```
restful하게 바라봤을 때 결국 id가 없다는 것은 해당 url이 존재하지 않은 것으로 판단 되므로 404가 조금 더 어울릴 것 같습니다.

2021-07-12 10:51 UTC, Pratiable commented on orders/views.py
> +                    item.delete()
수정했습니다!

2021-07-12 10:52 UTC, Pratiable commented on orders/views.py
> +                return JsonResponse({'message':'INVALID_ITEM'}, status=400)
넵 감사합니다! 404로 수정 완료 했습니다!

2021-07-13 01:04 UTC, Kang-kyunghun commented
goooooooood~!! 👍

2021-07-13 01:04 UTC, merged