[22기 서정민] 상품리스트 read, 필터링 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #15
Opened 2021-07-09 09:09 UTC by jungminsayho

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상품리스트 read, 필터링 구현
		 
## 수정 사항들 자세한 내용
- query parameter로 category 별 필터링 구현
- category=all 인 경우, 전체 상품 반환
- category 이름이 잘못 들어온 경우, Category.DoesNotExist 에러 발생
- query parameter가 잘못 들어온 경우, MultiValueDictKeyError 발생
- 추가 필터링 (판매순, 리뷰순, 가격순(높은순, 낮은순)) 구현 (sort)
- 추가필터링 query parameter에서 오타 발생 시, 필터링되지 않은 상품리스트 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 08:44 UTC, Kang-kyunghun requested changes

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +class ListingView(View):
```suggestion
class ProductsView(View):
```
view 이름은 어떤 자원을 활용하는 지를 나타내는 것이 좋습니다. product 상세와 구분하기 위해 Products로 바꾸는 것이 좋을 것 같습니다.

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/urls.py
> +    path('/list', ListingView.as_view()),
```suggestion
    path('', ListingView.as_view()),
```

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +
공백 제거해 주세요.

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'message': 'CATEGORY_DOES_NOT_EXIST'}, status=400)
except 구문들을 맨 아래로 내려서 가독성을 높여주세요.

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +            category = Category.objects.get(name=request.GET.get('category', ''))
category 값을 프론트에서 안 주면 어떻게 될까요?

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +                products = products.order_by(sort[request.GET.get('sort', '')])
여기도 sort 값을 못 받았을 때 어떻게 되나요?

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +                category = Category.objects.get(name='all')
category에 all이라는 데이터도 있나요?

2021-07-12 08:44 UTC, Kang-kyunghun commented on products/views.py
> +            if request.GET['category'] == 'all':
category에 값이 안 들어 올 때 전체 상품을 반환하는 형식으로 바꿔보세요.

2021-07-12 09:05 UTC, jungminsayho commented on products/urls.py
> +    path('/list', ListingView.as_view()),
이것도 수정했습니다!

2021-07-12 09:06 UTC, jungminsayho commented on products/views.py
> +
수정했습니다!

2021-07-12 09:07 UTC, jungminsayho commented on products/views.py
> +                category = Category.objects.get(name='all')
넵 전체상품을 반환하는 경우의 카테고리 이미지도 상단에 나타내기때문에, all이라는 카테고리도 따로 두었습니다!

2021-07-12 09:08 UTC, jungminsayho commented on products/views.py
> +class ListingView(View):
오넵! 변경했습니다!

2021-07-12 12:48 UTC, jungminsayho commented on products/views.py
> +                products = products.order_by(sort[request.GET.get('sort', '')])
sort 값을 받지 못했을 때, 앞에까지(카테고리까지) 필터링된 리스트를 보여주도록 수정하였습니다.

2021-07-12 12:49 UTC, jungminsayho commented on products/views.py
> +            if request.GET['category'] == 'all':
넵 수정하였습니다!

2021-07-12 12:49 UTC, jungminsayho commented on products/views.py
> +            category = Category.objects.get(name=request.GET.get('category', ''))
category 값을 전달받지 못했을 경우, 전체 상품을 반환하는 것으로 수정하였습니다!

2021-07-12 12:49 UTC, jungminsayho commented on products/views.py
> +            return JsonResponse({'message': 'CATEGORY_DOES_NOT_EXIST'}, status=400)
넵 수정하였습니다.

2021-07-14 06:35 UTC, Kang-kyunghun commented
1주일 동안 고생 많았습니다~~!!

2021-07-14 06:35 UTC, merged