[최현정] validator 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #19
Opened 2021-07-12 08:49 UTC by princenim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- validator 추가했습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 09:05 UTC, Kang-kyunghun requested changes

2021-07-12 09:05 UTC, Kang-kyunghun commented on utils.py
> +
공백 제거해 주세요.

2021-07-12 09:05 UTC, Kang-kyunghun commented on users/views.py
> +from users.models import Coupon, User
위에 import하는 라이브러리들 import 기준으로 정렬 해주세요.

2021-07-12 09:05 UTC, Kang-kyunghun commented on utils.py
> +        except jwt.exceptions.DecodeError:
except를 return func보다 아래로 내려 가독성을 높여 주세요.

2021-07-12 10:04 UTC, princenim commented on utils.py
> +
수정했습니다.

2021-07-12 10:18 UTC, princenim commented on users/views.py
> +from users.models import Coupon, User
수정했습니다.

2021-07-12 10:19 UTC, princenim commented on utils.py
> +        except jwt.exceptions.DecodeError:
수정했습니다!

2021-07-13 04:49 UTC, Kang-kyunghun requested changes

2021-07-13 04:49 UTC, Kang-kyunghun commented on utils.py
> +            user        = User.objects.get(id = payload['user_id'])
user가 database에 없을 때 예외처리 추가해 주세요

2021-07-13 04:49 UTC, Kang-kyunghun commented on orders/views.py
> +    # @login_decorator
데코레이터가 있다고 가정하고 주석 제거해 주세요.

2021-07-13 04:49 UTC, Kang-kyunghun commented on users/views.py
> +from json.decoder     import JSONDecodeError
가장 긴 단어 기준으로 1칸만 띄어 주세요.

2021-07-13 04:52 UTC, princenim commented on orders/views.py
> +    # @login_decorator
수정했습니다.

2021-07-13 04:54 UTC, princenim commented on users/views.py
> +from json.decoder     import JSONDecodeError
수정했습니다.

2021-07-13 05:22 UTC, princenim commented on utils.py
> +            user        = User.objects.get(id = payload['user_id'])
수정했습니다.

2021-07-13 06:21 UTC, Kang-kyunghun commented
LGTM

2021-07-13 06:21 UTC, merged