[22기 이준영] 장바구니에 있는 물건들 구매 기능 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #24
Opened 2021-07-13 05:11 UTC by Pratiable

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 products 구매 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 products 구매 기능 구현
- 재고량 체크 및 에러 반환
- 쿠폰 사용하여 쿠폰이 사용 되면 금액 할인 및 사용한 쿠폰 삭제
- 5만원 이상 주문하거나 첫 구매일경우 배송비 무료
- 포인트는 미구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 로직을 이렇게 길게 짜도 되는지 궁금합니다.......

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 09:53 UTC, Kang-kyunghun requested changes

2021-07-13 09:53 UTC, Kang-kyunghun commented on orders/views.py
> +            cart_items     = CartItem.objects.filter(user=signed_user)
전체 구매만 가능한가요?

2021-07-13 09:55 UTC, Kang-kyunghun commented
cart table과 order table이 동시에 update 되야 되므로 transaction을 걸어서 구현해 보세요.

2021-07-13 11:41 UTC, Pratiable commented on orders/views.py
> +            cart_items     = CartItem.objects.filter(user=signed_user)
넵 전체 구매로 구현하기로 했고 트랜잭션 걸고 쿼리도 조금 최적화 했습니다

2021-07-14 01:31 UTC, Kang-kyunghun requested changes

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +    @transaction.atomic
데코레이터 걸고, whit로도 transaction을 걸었는데, 2개다 사용한 이유가 있나요?

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +                return JsonResponse({"message":"NO_ITEMS_IN_CART"}, status=400)
```suggestion
            if not cart_items.exists():
                return JsonResponse({"message":"NO_ITEMS_IN_CART"}, status=400)
```
존재 유무를 판단 할 때는 exists()을 이용해 주세요. 안 그러면 모든 데이터를 다 가져온 뒤에 존재 유무를 판단하게 됩니다.

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +
공백 제거해 주세요.

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +
공백 제거해 주세요.

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +
공백 제거해 주세요.

2021-07-14 01:31 UTC, Kang-kyunghun commented on orders/views.py
> +                            or total_price < 50000
하드코딩한 숫자들 상수화 해주세요.

2021-07-14 01:41 UTC, Pratiable commented on orders/views.py
> +    @transaction.atomic
아 어제 이것저것 해보다가 try except안으로 집어넣으려고 with를 썼는데 실수로 지우지 못했습니다 죄송합니다!

2021-07-14 01:41 UTC, Pratiable commented on orders/views.py
> +                return JsonResponse({"message":"NO_ITEMS_IN_CART"}, status=400)
넵 수정했습니다

2021-07-14 01:41 UTC, Pratiable commented on orders/views.py
> +
제거했습니다!

2021-07-14 01:41 UTC, Pratiable commented on orders/views.py
> +
제거했습니다!

2021-07-14 01:41 UTC, Pratiable commented on orders/views.py
> +
제거했습니다!

2021-07-14 02:12 UTC, Pratiable commented on orders/views.py
> +                            or total_price < 50000
상수화 진행 하였습니다!

2021-07-14 10:44 UTC, Pratiable commented
```
            if coupon_id:
                if not UserCoupon.objects.filter(coupon=coupon_id, user=signed_user).exists():
                    return JsonResponse({'message':'INVALID_COUPON'}, status=400)

                UserCoupon.objects.filter(coupon=coupon_id, user=signed_user).first().delete()

                total_price -= Coupon.objects.get(pk=coupon_id).value
                total_price = 0 if total_price <= 0 else total_price
```
경훈님 이 부분은 if문 합치려고 했는데 합치면 아래 부분을 넣을 수 없어서 고민입니다... 도와주세요..........죄송합니다.........

2021-07-15 08:44 UTC, merged

2021-07-15 08:45 UTC, Kang-kyunghun commented
고생 많으셨습니다~~!! 리펙토링을 많이 해야 될 것 같지만요~