[이준영] 장바구니 리스트 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #4
Opened 2021-07-08 01:53 UTC by Pratiable

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 리스트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 리스트 구현
- 가능한 경우의 수 예외처리 진행
- 총 금액은 표시 없이 진행
- 현재 토큰을 받아 올 수 없어서 url쿼리메세지로 user Id 불러옴

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.) 
- 프론트에서 금액 계산을 해주는게 수량 변경 시 다시 리스트를 get 할 필요가 없다고 생각해서 총액은 넣지 않았습니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 04:34 UTC, Kang-kyunghun requested changes

2021-07-08 04:34 UTC, Kang-kyunghun commented on orders/views.py
> +            user       = User.objects.get(pk=request.GET.get('user_id'))
user의 정보는 프로트에서 주는 데이터로 가져오는 것이 아니고 토큰을 통해 받아야 합니다. 
그러면 토큰을 통해 어떻게 유저의 정보를 받을 수 있을까요?
위스타그램 마무리 시간에 설명한 로그인 데코레이터에 대해 한 번 생각해 보세요.

2021-07-08 04:34 UTC, Kang-kyunghun commented on orders/views.py
> +                return JsonResponse({'MESSAGE':'NO_ITEMS_IN_CART'}, status=200)
유저가 상품을 담은 것이 없다면 이 경우에는 빈 리스트를 보내주면 됩니다.

2021-07-08 04:34 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PRODUCT'}, status=400)
이 예외처리를 사용한 이유를 코멘트로 남겨 주세요.

2021-07-08 04:34 UTC, Kang-kyunghun commented on orders/views.py
> +            return JsonResponse({'CART_ITEMS':cart_lists}, status=200)
CART_ITEMS 이 키 값은 프론트랑 맞춘 내용인가요?
보통은 JS의 컨벤션으로 가거나, python 컨벤션 둘 중 하나를 선택하게 되는데, 어떻게 결정한 것이지 코멘트로 남겨 주세요.

2021-07-08 05:07 UTC, Pratiable commented on orders/views.py
> +            return JsonResponse({'CART_ITEMS':cart_lists}, status=200)
Camel Case로 합의헀습니다!

2021-07-08 06:35 UTC, Pratiable commented on orders/views.py
> +            user       = User.objects.get(pk=request.GET.get('user_id'))
수정했습니다!

2021-07-08 06:36 UTC, Pratiable commented on orders/views.py
> +                return JsonResponse({'MESSAGE':'NO_ITEMS_IN_CART'}, status=200)
넵 수정했습니다!

2021-07-08 07:05 UTC, Pratiable commented on orders/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PRODUCT'}, status=400)
Product가 삭제되었을 때 예외처리 했는데 생각해 보니 없을땐 표시 안하고 넘어가는게 맞는 것 같아서 로직 수정했습니다!

2021-07-08 08:57 UTC, Kang-kyunghun requested changes

2021-07-08 08:57 UTC, Kang-kyunghun commented on orders/views.py
> +                return JsonResponse({'cartItems':cart_lists}, status=200)
빈 list라면 아래 for문이 동작하지 않아 어차피 빈 list가 반환 됩니다.
즉, 이 코드는 없어도 될 것 같습니다.

2021-07-08 08:57 UTC, Kang-kyunghun commented on orders/views.py
> +            for item in items:
장바구니 목록으르 for문을 이용해 아주 잘 만들었습니다.
혹시 해당 코드를 list comprehension으로 바꿀수 있다는 것을 알고 계신가요? list comprehension으로 바꾸면 내부적으로 연산 속도도 빠르고 가독성도 높일 수 있습니다.
위의 코드를 list comprehension으로 바꿔 주세요~

2021-07-08 08:57 UTC, Kang-kyunghun commented on orders/views.py
> +                product = item.product_options.product
없어도 될 것 같은데 일단 해당 코드 없이 list comprehension으로 바꿔 보세요.

2021-07-08 10:16 UTC, Pratiable commented on orders/views.py
> +                return JsonResponse({'cartItems':cart_lists}, status=200)
감사합니다 생각을 못했었습니다! 제거했습니다!

2021-07-08 10:16 UTC, Pratiable commented on orders/views.py
> +                product = item.product_options.product
넵 list comprehension으로 수정했습니다

2021-07-08 10:16 UTC, Pratiable commented on orders/views.py
> +            for item in items:
넵 list comprehension으로 수정했습니다

2021-07-09 01:37 UTC, Kang-kyunghun requested changes

2021-07-09 01:37 UTC, Kang-kyunghun commented on orders/views.py
> +                for item in items
```suggestion
                    } for item in items
```

2021-07-09 01:37 UTC, Kang-kyunghun commented on orders/views.py
> +                for item in items
이 부분만 고치면 될 것 같습니다.

2021-07-09 01:39 UTC, Pratiable commented on orders/views.py
> +                for item in items
수정했습니다!

2021-07-09 05:39 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-07-09 05:39 UTC, merged