[22기 서정민] 상품페이지 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #6
Opened 2021-07-08 08:36 UTC by jungminsayho

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품페이지 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- path parameter를 이용하여 product_id를 받음
- 상품페이지에 필요한 내용 response로 반환
- 존재하지 않는 product_id를 받을 경우 DoesNotExist 에러 처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 09:05 UTC, Kang-kyunghun requested changes

2021-07-08 09:05 UTC, Kang-kyunghun commented on gogigak/urls.py
> +    path('', include('products.urls')),
url을 product로 안 하고 ''으로 한 이유가 있나요?

2021-07-08 09:05 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'message': 'PRODUCT_NOT_FOUND'}, status=400)
product의 존재 여부에 대한 예외처리 잘 하셨습니다.

except로 예외처리 하는 방법 말고 if문과 장고 ORM의 exists() method을 이용해서 예외처리 해보시겠어요? 
except로 예외처리 하는 것보다 서버의 자원을 덜 사용하는 것으로 알려져 있습니다.

2021-07-08 16:11 UTC, jungminsayho commented on gogigak/urls.py
> +    path('', include('products.urls')),
같은 products 앱에 들어가는 다른 View들을 함께 고려해보고 혼돈이 생길 수 있을 것 같아서 그렇게 했었는데,
다시 생각해보고 팀원들과 논의해본 결과, products로 앱 경로를 수정하는 방향으로 바꾸었습니다!

2021-07-08 16:12 UTC, jungminsayho commented on products/views.py
> +            return JsonResponse({'message': 'PRODUCT_NOT_FOUND'}, status=400)
오 네 알겠습니다, 말씀하신대로 처리해보았습니다!

2021-07-09 01:39 UTC, Kang-kyunghun commented
LGTM~~!! 👍

2021-07-09 01:39 UTC, merged