Add: user-signin
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #7
Opened 2021-07-08 08:41 UTC by princenim

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 09:13 UTC, Kang-kyunghun requested changes

2021-07-08 09:13 UTC, Kang-kyunghun commented on .vscode/settings.json
> +{
gitignore에 추가해 주시고 github에 안 올라오게 해주세요.

2021-07-08 09:13 UTC, Kang-kyunghun commented on users/views.py
> +import jwt
```suggestion
import json
import re
import bcrypt
import jwt
from json.decoder import JSONDecodeError
```
이게 조금 더 가독성이 좋을 것 같습니다.

2021-07-08 09:13 UTC, Kang-kyunghun commented on users/views.py
> +
공백 제거해 주세요.

2021-07-08 09:13 UTC, Kang-kyunghun commented on users/views.py
> +
공백 제거해 주세요.

2021-07-08 09:13 UTC, Kang-kyunghun commented on users/views.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status = 401)
user의 존재 여부에 대한 예외처리 잘 하셨습니다.

except로 예외처리 하는 방법 말고 if문과 장고 ORM의 exists() method을 이용해서 예외처리 해보시겠어요?
except로 예외처리 하는 것보다 서버의 자원을 덜 사용하는 것으로 알려져 있습니다.

2021-07-08 11:02 UTC, princenim commented on users/views.py
> +import jwt
수정했습니다

2021-07-08 11:04 UTC, princenim commented on users/views.py
> +
수정했습니다.

2021-07-08 11:05 UTC, princenim commented on .vscode/settings.json
> +{
수정했습니다.

2021-07-08 11:06 UTC, princenim commented on users/views.py
> +
수정했습니다.

2021-07-08 11:40 UTC, princenim commented on users/views.py
> +            return JsonResponse({"message" : "INVALID_USER"}, status = 401)
수정했습니다.

2021-07-09 01:34 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-07-09 01:34 UTC, merged