[22기 이준영] 장바구니 제품 추가 기능 구현
wecode-bootcamp-korea/22-1st-Gogigak-backend pull request #9
Opened 2021-07-09 06:14 UTC by Pratiable

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 제품 추가 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 장바구니 제품 추가 기능 구현
- 제품 수량 이상 담을 시 에러 return
- 이미 상품이 장바구니에 존재할 시 새로 row를 만들지 않고 수량만 추가
- 각종 에러 처리

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-09 10:44 UTC, Kang-kyunghun requested changes

2021-07-09 10:44 UTC, Kang-kyunghun commented on orders/views.py
> +            product_option = ProductOption.objects.get(product=product, option=option)
예외처리 부분을 맨 위로 올리고 데이터를 가져오는 부분을 밑에서 같이 하면 좋을 것 같아요.
중간에 data을 가져왔는데, 다른 예외처리에 걸려 함수가 끝나게 되면, 데이터 베이스에서 데이터를 가져오는데 사용한 자원을 낭비하는 것이 됩니다.

2021-07-09 10:44 UTC, Kang-kyunghun commented on orders/views.py
> +                cart_item = CartItem.objects.get(user = signed_user, product_options = product_option)
get_or_create method를 사용해서 아래 create 하는 부분까지 하나로 합쳐 보세요

2021-07-09 12:23 UTC, Pratiable commented on orders/views.py
> +                cart_item = CartItem.objects.get(user = signed_user, product_options = product_option)
제가 get_or_create를 써보려고 했는데 만약에 quantity를 argument에 주게되면 장바구니에 똑같은 상품이 있는데 수량만 달라도 row가 생성돼서 문제가 되고(만약 이런 방식으로 진행하고 필터로 수량만 다르고 유저와 제품이 똑같은 것을 확인해서 서로 수량을 합치고 row를 삭제한다고 하면 더 비효율적일 것 같다는 생각을 했습니다), 만약에 quantity를 빼고 get_or_create를 사용하게 되면 get에서는 내용을 가져올 수 있어도 get으로 가져올 것이 없을 때 quantity값이 들어가지 않았기 때문에 IntegrityError가 발생합니다.
일단 팀원들과 상의하면서 방법을 생각 해 봤는데 저희끼리는 도저히 답이 나오지 않아서 Comment드립니다!
혹시 제가 생각하지 못한 부분이 있다면 힌트 주시면 더 고민을 해보도록 하겠습니다!

2021-07-09 12:24 UTC, Pratiable commented on orders/views.py
> +            product_option = ProductOption.objects.get(product=product, option=option)
수정했습니다!

2021-07-12 00:30 UTC, Kang-kyunghun commented on orders/views.py
> +                cart_item = CartItem.objects.get(user = signed_user, product_options = product_option)
get_or_create 사용할 때 default 옵션 주셨나요? 이게 create 할 때 기본값 넣어 주는 옵션인데, 안 넣으셨다면, 넣어보고 한 번 해보시겠어요~?

2021-07-12 04:52 UTC, Pratiable commented on orders/views.py
> +                cart_item = CartItem.objects.get(user = signed_user, product_options = product_option)
경훈님 감사합니다 수정 했습니다
앞으로는 공식문서를 먼저 확인해보도록 하곘습니다............ 감사합니다!!!!!!!!!!!!!!!!!!!!

2021-07-12 08:26 UTC, Pratiable commented on orders/views.py
> +                cart_item = CartItem.objects.get(user = signed_user, product_options = product_option)
수정 후 푸쉬했습니다!

2021-07-12 08:37 UTC, Kang-kyunghun commented
고생 많았습니다~~

2021-07-12 08:37 UTC, merged